IGAPP-437: Notify mattermost over failing and delivering builds

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,16 +41,79 @@ commands:
                 name: Linting check
             - store_test_results:
                 path: << parameters.directory >>/reports/lint
-    notify_failed:
-        description: Notifies about jobs which have failed
+    notify:
+        description: Send a notification (to Mattermost) at the end of a job, based on success or failure. Must be the last step in a job.
+        parameters:
+            channel:
+                default: app
+                type: string
+            failure_mentions:
+                default: '@max.amman @stefanie.metzger @sarah.sporck @steffen.kleinle'
+                type: string
+            failure_message:
+                default: ':fire: The [${CIRCLE_JOB}](${CIRCLE_BUILD_URL}) job has failed on the main branch! :fire:'
+                type: string
+            only_for_branch:
+                default: main
+                type: string
+            success_mentions:
+                default: ""
+                type: string
+            success_message:
+                default: ""
+                type: string
         steps:
-            - slack/status:
-                fail_only: true
-                failure_message: ':fire: The $CIRCLE_JOB job has failed on the main branch! :fire:'
-                include_job_number_field: false
-                mentions: maxammann,st,UV99P8ETW
-                only_for_branches: main
-                webhook: ${SLACK_URL}
+            - run:
+                command: |
+                    echo 'export MM_MESSAGE="<< parameters.failure_message >>\n<< parameters.failure_mentions >>"' >> $BASH_ENV
+                name: Mattermost - Failure message
+                when: on_fail
+            - run:
+                command: |
+                    echo 'export MM_MESSAGE="<< parameters.success_message >>\n<< parameters.success_mentions >>"' >> $BASH_ENV
+                name: Mattermost - Success message
+                when: on_success
+            - run:
+                command: |
+                    #!/bin/bash
+
+                    Send_notification() {
+                        if [ << parameters.only_for_branch >> -ne "${CIRCLE_BRANCH}" ]; then
+                            echo "Not on << parameters.only_for_branch >> branch. Skipping."
+                            exit 0
+                        fi
+
+                        if [ -z "${MM_MESSAGE}" ]; then
+                            echo "No message set. Skipping."
+                            exit 0
+                        fi
+
+                        if [ -z "${MM_WEBHOOK}" ]; then
+                            echo "NO MATTERMOST WEBHOOK SET"
+                            echo "Please add the environment variable \"MM_WEBHOOK\" in the settings for this project."
+                            exit 1
+                        fi
+
+                        STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -H 'Content-type: application/json' \
+                            --data \
+                            "{
+                              \"channel\": \"<< parameters.channel >>\",
+                              \"username\": \"circleci\",
+                              \"text\": \"${MM_MESSAGE}\"
+                            }" "${MM_WEBHOOK}")
+
+                        if [ "$STATUS" -ne "200" ]; then
+                            echo "Notification not sent due to an error. Status: $STATUS. Please check the webhook URL"
+                            exit 1
+                        fi
+
+                        echo "Notification sent!"
+                        exit 0
+                      }
+
+                      Send_notification
+                name: Mattermost Status Alert
+                when: always
     prepare_workspace:
         description: Attach the workspace at ~/attached_workspace and list its contents
         steps:
@@ -250,7 +313,7 @@ jobs:
                     - << parameters.build_config_name >>.apk
                     - << parameters.build_config_name >>.android.bundle.map
                 root: native/android
-            - notify_failed
+            - notify
     build_ios:
         environment:
             FASTLANE_SKIP_UPDATE_CHECK: true
@@ -296,7 +359,7 @@ jobs:
                 paths:
                     - << parameters.build_config_name >>.ipa
                 root: native/ios/output/gym
-            - notify_failed
+            - notify
     build_web:
         docker:
             - image: circleci/node:12.16.3
@@ -334,7 +397,7 @@ jobs:
                 paths:
                     - dist
                 root: web
-            - notify_failed
+            - notify
     bump_version:
         docker:
             - image: circleci/node:12.16.3
@@ -383,7 +446,7 @@ jobs:
                 paths:
                     - environment_variables
                 root: ./
-            - notify_failed
+            - notify
     check_native:
         docker:
             - image: circleci/node:12.16.3
@@ -409,7 +472,7 @@ jobs:
                 directory: api-client
             - unit_test:
                 directory: translations
-            - notify_failed
+            - notify
     check_web:
         docker:
             - image: circleci/node:12.16.3
@@ -436,7 +499,7 @@ jobs:
                 directory: api-client
             - unit_test:
                 directory: translations
-            - notify_failed
+            - notify
     deliver_android:
         docker:
             - image: circleci/android:api-29-node
@@ -483,7 +546,7 @@ jobs:
                 command: bundle exec fastlane android sentry_upload build_config_name:<< parameters.build_config_name >> sourcemap_path:attached_workspace/<< parameters.build_config_name >>.android.bundle.map version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
                 name: '[FL] Upload to Sentry'
                 working_directory: native
-            - notify_failed
+            - notify
     deliver_ios:
         environment:
             FASTLANE_SKIP_UPDATE_CHECK: true
@@ -539,7 +602,7 @@ jobs:
                 command: bundle exec fastlane ios sentry_upload version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} build_config_name:<< parameters.build_config_name >> sourcemap_path:attached_workspace/<< parameters.build_config_name >>.ios.bundle.map
                 name: '[FL] Upload to Sentry'
                 working_directory: native
-            - notify_failed
+            - notify
     deliver_web:
         docker:
             - image: circleci/node:12.16.3
@@ -581,7 +644,7 @@ jobs:
                     - run:
                         command: tools/sentry-release integreat-test-cms "${NEW_VERSION_NAME}" ~/attached_workspace/dist/integreat-test-cms
                         name: 'Sentry Upload: integreat-test-cms'
-            - notify_failed
+            - notify
     e2e_android:
         docker:
             - image: circleci/android:api-29-node
@@ -600,7 +663,7 @@ jobs:
                 command: bundle exec fastlane android browserstack_e2e_tests apk_path:attached_workspace/integreat-e2e.apk
                 name: '[FL] Android E2E Tests on Browserstack'
                 working_directory: native
-            - notify_failed
+            - notify
     e2e_ios:
         docker:
             - image: circleci/android:api-29-node
@@ -619,7 +682,7 @@ jobs:
                 command: bundle exec fastlane ios browserstack_e2e_tests ipa_path:attached_workspace/integreat-e2e.ipa
                 name: '[FL] iOS E2E Tests on Browserstack'
                 working_directory: native
-            - notify_failed
+            - notify
     move_release_notes:
         docker:
             - image: circleci/node:12.16.3
@@ -633,7 +696,7 @@ jobs:
             - run:
                 command: tools/move-release-notes move-to ${NEW_VERSION_NAME} --deliverino-private-key ${DELIVERINO_PRIVATE_KEY} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --branch ${CIRCLE_BRANCH}
                 name: Move release notes
-            - notify_failed
+            - notify
     notify_android:
         docker:
             - image: circleci/node:12.16.3
@@ -652,12 +715,10 @@ jobs:
                 command: tools/github-release create android ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --deliverino-private-key ${DELIVERINO_PRIVATE_KEY} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --release-notes "$(tools/parse-release-notes parse --android --language en)"<<^ parameters.production_delivery >> --development-release<</ parameters.production_delivery >>
                 name: Create github release
             - run:
-                command: echo "export SLACK_RELEASE_NOTES=$(tools/parse-release-notes parse --android --language en)" >> ${BASH_ENV}
-                name: Create slack release notes
-            - slack/notify:
-                message: <<^ parameters.production_delivery >>[Development] <</ parameters.production_delivery >>Integreat and Malte ${NEW_VERSION_NAME} have been released successfully on Android!\n${SLACK_RELEASE_NOTES}
-                webhook: ${SLACK_URL}
-            - notify_failed
+                command: echo "export RELEASE_NOTES=$(tools/parse-release-notes parse --android --language en)" >> ${BASH_ENV}
+                name: Create release notes
+            - notify:
+                success_message: <<^ parameters.production_delivery >>[Development] <</ parameters.production_delivery >>Integreat and Malte ${NEW_VERSION_NAME} have been released successfully on Android!\n${RELEASE_NOTES}
     notify_ios:
         docker:
             - image: circleci/node:12.16.3
@@ -676,12 +737,10 @@ jobs:
                 command: tools/github-release create ios ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --deliverino-private-key ${DELIVERINO_PRIVATE_KEY} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --release-notes "$(tools/parse-release-notes parse --ios --language en)"<<^ parameters.production_delivery >> --development-release<</ parameters.production_delivery >>
                 name: Create github release
             - run:
-                command: echo "export SLACK_RELEASE_NOTES=$(tools/parse-release-notes parse --ios --language en)" >> ${BASH_ENV}
-                name: Create slack release notes
-            - slack/notify:
-                message: <<^ parameters.production_delivery >>[Development] <</ parameters.production_delivery >>Integreat and Malte ${NEW_VERSION_NAME} have been released successfully on iOS!\n${SLACK_RELEASE_NOTES}
-                webhook: ${SLACK_URL}
-            - notify_failed
+                command: echo "export RELEASE_NOTES=$(tools/parse-release-notes parse --ios --language en)" >> ${BASH_ENV}
+                name: Create release notes
+            - notify:
+                success_message: <<^ parameters.production_delivery >>[Development] <</ parameters.production_delivery >>Integreat and Malte ${NEW_VERSION_NAME} have been released successfully on iOS!\n${RELEASE_NOTES}
     notify_web:
         docker:
             - image: circleci/node:12.16.3
@@ -696,12 +755,10 @@ jobs:
                 command: tools/github-release create web ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --deliverino-private-key ${DELIVERINO_PRIVATE_KEY} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --release-notes "$(tools/parse-release-notes parse --web --language en)"
                 name: Create github release
             - run:
-                command: echo "export SLACK_RELEASE_NOTES=$(tools/parse-release-notes parse --web --language en)" >> ${BASH_ENV}
-                name: Create slack release notes
-            - slack/notify:
-                message: WebApp version ${NEW_VERSION_NAME} was delivered successfully to integreat.app and malteapp.de!\n${SLACK_RELEASE_NOTES}
-                webhook: ${SLACK_URL}
-            - notify_failed
+                command: echo "export RELEASE_NOTES=$(tools/parse-release-notes parse --web --language en)" >> ${BASH_ENV}
+                name: Create release notes
+            - notify:
+                success_message: WebApp version ${NEW_VERSION_NAME} was delivered successfully to integreat.app and malteapp.de!\n${RELEASE_NOTES}
 orbs:
     slack: circleci/slack@3.4.2
 parameters:
